#!/bin/bash

set -e

IMAGE_NAME=dustymugs/pgplus

build_image() {
  POSTGIS_RELEASE=$1
  IMAGE=$IMAGE_NAME:$BASE

  docker build --pull -t "$IMAGE" --build-arg POSTGIS_RELEASE=$POSTGIS_RELEASE .
  docker push $IMAGE
}

build_image "12-3.0"

wait
